#require 'pry'
#require 'nokogiri'
#require 'open-uri'

require_relative '../lib/assumption/cli'
require_relative '../lib/assumption/chart_data_set'
require_relative '../lib/assumption/version'
require_relative '../lib/assumption/game'
require_relative '../lib/assumption/data_importer'
require_relative '../lib/assumption/song'
require_relative '../lib/assumption/concerns/uni_functions'
