require 'tco'
require 'open-uri'
require 'nokogiri'
require 'io/console'
require 'net/http'
require 'pry'

require_relative '../lib/assumption/version'
require_relative '../lib/assumption'
require_relative '../lib/assumption/concerns/uni_functions'
require_relative '../lib/assumption/cli'
require_relative '../lib/assumption/chart_data_set'
require_relative '../lib/assumption/game'
require_relative '../lib/assumption/data_importer'
require_relative '../lib/assumption/song'
